//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comic()
        {
            this.Comic_Cate_Comic = new HashSet<Comic_Cate_Comic>();
            this.Comic_chapter = new HashSet<Comic_chapter>();
            this.Follow = new HashSet<Follow>();
        }
    
        public string Comic_id { get; set; }
        public string UP_id { get; set; }
        public string Comic_cover { get; set; }
        public string Comic_name { get; set; }
        public string Comic_writer { get; set; }
        public string Comic_intro { get; set; }
        public string Comic_chapter_nums { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comic_Cate_Comic> Comic_Cate_Comic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comic_chapter> Comic_chapter { get; set; }
        public virtual UP UP { get; set; }
        public virtual Comment Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follow> Follow { get; set; }
    }
}
