//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comic_pager
    {
        public int Comic_page { get; set; }
        public Nullable<int> Comic_chapter_id { get; set; }
        public Nullable<int> Comic_page_nums { get; set; }
        public string Comic_picpage { get; set; }
    
        public virtual Comic_chapter Comic_chapter { get; set; }
    }
}
