//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follow
    {
        public int Follow_id { get; set; }
        public int Comic_id { get; set; }
        public int User_id { get; set; }
        public System.DateTime Follow_time { get; set; }
    
        public virtual Comic Comic { get; set; }
        public virtual User User { get; set; }
    }
}
