//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_Cate_Goods
    {
        public int Goods_Cate_id { get; set; }
        public int Cate_id { get; set; }
        public int Goods_id { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Goods_Cate Goods_Cate { get; set; }
    }
}
