//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_details
    {
        public string Order_details_id { get; set; }
        public string Orders_id { get; set; }
        public string Ware_id { get; set; }
        public string Ware_num { get; set; }
    }
}
