//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribe
    {
        public string Subscribe_id { get; set; }
        public string User_id { get; set; }
        public string Comic_detail_id { get; set; }
        public string Subscribe_time { get; set; }
        public string Subscribe_nums { get; set; }
        public string Subscribe_price { get; set; }
    
        public virtual Comic_chapter Comic_chapter { get; set; }
        public virtual User User { get; set; }
    }
}
