//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.Video_detail = new HashSet<Video_detail>();
        }
    
        public string Video_id { get; set; }
        public string UP_id { get; set; }
        public string Video_name { get; set; }
        public string Video_intro { get; set; }
        public string Video_nums { get; set; }
    
        public virtual Collection Collection { get; set; }
        public virtual UP UP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video_detail> Video_detail { get; set; }
    }
}
