//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ware_Cate
    {
        public Nullable<int> Cate_id { get; set; }
        public Nullable<int> Ware_id { get; set; }
        public int Ware_Cate_id { get; set; }
    
        public virtual Goods_Cate Goods_Cate { get; set; }
        public virtual Ware Ware { get; set; }
    }
}
