//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.Collection = new HashSet<Collection>();
            this.Goods = new HashSet<Goods>();
            this.Video_Access = new HashSet<Video_Access>();
            this.Video_detail = new HashSet<Video_detail>();
        }
    
        public int Video_id { get; set; }
        public int UP_id { get; set; }
        public string Video_name { get; set; }
        public string Video_intro { get; set; }
        public int Video_nums { get; set; }
        public string Audiences { get; set; }
        public string Colors { get; set; }
        public string Territory { get; set; }
        public string Usage { get; set; }
        public string Contents { get; set; }
    
        public virtual Audiences Audiences1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collection { get; set; }
        public virtual Colors Colors1 { get; set; }
        public virtual Contents Contents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goods> Goods { get; set; }
        public virtual Territory Territory1 { get; set; }
        public virtual UP UP { get; set; }
        public virtual Usage Usage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video_Access> Video_Access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video_detail> Video_detail { get; set; }
    }
}
